FROM thekoreanbeaver/go-alpine-firestore:latest

RUN set -ex; \
    apk update; \
    apk add --no-cache git

RUN mkdir -p /go/src/github.com/remychantenay/fuego
ADD . /go/src/github.com/remychantenay/fuego
WORKDIR /go/src/github.com/remychantenay/fuego

CMD CGO_ENABLED=0 go test . -v -count=1